title: DemoMatlabJavaDefaultCtor Documentation
email: 
description: Documentation for DemoMatlabJavaDefaultCtor

baseurl: ""
url: ""

github_username: apjanke
github:
  repository_nwo: apjanke/DemoMatlabJavaDefaultCtor
forkme_nwo: apjanke/DemoMatlabJavaDefaultCtor
footer-links:
  github: apjanke/DemoMatlabJavaDefaultCtor

permalink: pretty

exclude:
  - Gemfile*
  - README.md
  - make_doc

markdown: kramdown
theme: jekyll-theme-slate
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    default_lang: matlab
asciidoc: {}
asciidoctor:
   base_dir: :docdir
   safe: unsafe
   attributes:
     stem: 
     imagesdir: /images
     source-highlighter: pygments
     pygments-stylesheet: css/asciidoc-pygments.css

keep_files:
- images
plugins:
  - asciidoctor-diagram
  - jekyll-asciidoc
  - jekyll-last-modified-at
  - jekyll-toc          # https://github.com/toshimaru/jekyll-toc
  - jekyll-sitemap      # https://github.com/jekyll/jekyll-sitemap
  # Not sure about this one:
  # - jekyll-paginate
